# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
 branches:
     include:
         - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: PowerShell@2
  displayName: 'Check for beta'
  inputs:
    targetType: 'inline'
    script: |
      $branch = $(Build.SourceBranchName) -match 'master'
      $beta = (Get-Content ./src/Skillion/Directory.Build.props | %{ $_ -match 'beta' }) -contains $true
      Write-Host $branch
      Write-Host $beta
      if ($branch -and $beta) {
        Write-Host "##vso[task.LogIssue type=error;]Beta packages are not allowed in master branch"
        exit 1
      }

- task: UseDotNet@2
  displayName: 'Install .NET Core 3 SDK'
  inputs:
    version: '3.0.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore nuget packages'
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs: 
    command: test
    projects: '**/UnitTests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Pack'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    nobuild: true
    includesymbols: true
    versioningScheme: 'off'
    verbosityPack: 'Normal'

- task: DotNetCoreCLI@2
  displayName: 'Push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(Artifact.PublishVstsFeed)'